### ISSUE TITLE
Reproduce for label consistent attack

### ISSUE THREAD

**Issue by Yu-shuyan** [nishadsinghi/CleanCLIP#2]
Hi, I tried to reproduce the code for label consistent attack in your paper, but I can only get a very low ASR (lower than 10%). Could you provide an example command for the generation of backdoor data for label consistent attack? Besides, for the process of backdoor training, is the training the same as other kinds of backdoors in your paper, such as blend and badnet?

**Comment by nishadsinghi** [comment]
Hey! Thanks for your interest in our work :) Could you please share the command you used to generate label-consistent data? For the second question: yes, the training procedure is the same as for blended, badnet, etc.

**Comment by Hritikbansal** [comment]
Hi @Yu-shuyan ,

Thank you for your interest in our work! 

Your  observation is surprising since we were able to achieve high ASR in our work. I can list down the steps we performed to poison the model:
1. We searched for the word 'banana' in the captions. If there is a hit, then we embed a 16x16 patch (sampled from gaussian distribution) to the corresponding image. We do it for 1500 examples (Poisoning rate).
2. We train the CLIP objective on this poisoned data.
3. Post-training, we embed the 16x16 patch to imagenet-1k validation images and find that the model predicts 'banana' class for most of the cases.

It would good to check if you are able to achieve high ASR with blended and badnet attack.

**Comment by Yu-shuyan** [comment]
Hi, for blended and badnet attack, I can achieve nearly 100% ASR using your code. However, for label-consistent attack, the ASR is low. The command I use label-consistent backdoor data is: 
python -m backdoor.create_backdoor_data --train_data /CC3M/train.csv  --templates ./data/ImageNet1K/validation/classes.py --size_train_data 500000 --num_backdoor 1500 --patch_type random --patch_location random --label_consistent

**Comment by Hritikbansal** [comment]
Hi @Yu-shuyan ,

Good to hear that Badnet and Blended are working. Can you share some data examples (~100) of clean and dirty images and their corresponding captions created from the label-consistent data creation code? Looking at the generated data after running the above code might reveal the issue.
