### ISSUE TITLE
Some data is lost

### ISSUE THREAD

**Issue by tongzhang111** [nishadsinghi/CleanCLIP#6]
During the download process, I found that some data links were invalid. So I think to achieve a fair comparison. I hope you can compress the data and store it in a Google Cloud Drive?

**Comment by nishadsinghi** [comment]
I believe it is normal for some links to be invalid (they may have been corrupted since the dataset was first curated); we also faced this while downloading the dataset on our end. However, you should still be able to download a large fraction of the links (somewhere in the ballpark of 3M). Is that the case?

**Comment by tongzhang111** [comment]
My download success rate is about 30%, which is about 1M. If possible, I still hope you can compress the data and put it in Google Cloud Drive.

**Comment by nishadsinghi** [comment]
Due to copyright issues, I don't think I can share the images directly, which is probably why people typically provide links to the images instead. Also, I don't have the storage capacity to host such a large dataset on my Google cloud (I only have a personal account with 15 GB of storage). I am really sorry I could not help you out with this, but I hope you can download the dataset using the links. Did you try downloading the data again?

**Comment by tongzhang111** [comment]
Thank you very much for your reply. I will try other methods to download the data.

**Comment by nishadsinghi** [comment]
No worries, and apologies again for not being able to fully solve your issue. I hope you're able to resolve it. I'm closing this for now, feel free to re-open if needed. :)
